### ISSUE TITLE
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dishRepository': Invocation of init method failed; nested exception is org.springframework.data.mapping.PropertyReferenceException: No property findAll found for type Dish!

### ISSUE THREAD

**Issue by mshubhank** [microsoft/spring-data-gremlin#228] opened 2019-06-07 12:11 UTC
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
* placeholder

## Current Behavior
* placeholder

## Possible Solution
* placeholder

## Steps to Reproduce (for bugs)
* step-1
* step-2
* ...

## Snapshot Code for Reproduce 
```java
@SpringBootApplication
public class Application {
    public static void main(String... args) {
        SpringApplication.run(Application.class, args);
    }
}
```

## Branch
* placeholder

## Your Environment
* Version used:
* Operating System and version (desktop or mobile):
* SDK version:

**Comment by Incarnation-p-lee** [comment] 2019-06-10 02:09
@mshubhank Thanks for issue this, could you please provide more information about this issue, like spring boot version, spring-data-gremlin version, as well as minimal code for reproducing ?

**Comment by chenrujun** [comment] 2021-03-09 06:59
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 06:59 UTC
Labels: azure-spring, gremlin
