### ISSUE TITLE
Exception "No such property: g for class: Script" when working with JanusGraph on IBM Cloud

### ISSUE THREAD

**Issue by frenki-d** [microsoft/spring-data-gremlin#197] opened 2019-02-05 09:38 UTC
Hi! I created a JanusGraph Server using IBM Compose and tried to run your example on it.

Connection with my remote JanusGraph server is established, but any method that works with data in my graph fails with exception: `com.microsoft.spring.data.gremlin.exception.GremlinQueryException: unable to complete query from gremlin; nested exception is java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: No such property: g for class: Script22`

What am I doing wrong? From Gremlin console everything works fine.

**Comment by Incarnation-p-lee** [comment] 2019-02-05 10:12
@frenki-d 
Can you provide more sample code and information about this issue ? By the way, this package focus on gremlin-server which independent to backend db. If backend graph db has some specific implemenation, you may got some unexpecte result.

**Comment by frenki-d** [comment] 2019-02-05 11:44
@Incarnation-p-lee, I checked out https://github.com/Microsoft/spring-data-gremlin/tree/master/examples, changed application.yml to:

```
 gremlin:
   endpoint: portal-ssl486-36.simpozio-janusgraph-test.1243096254.composedb.com
   port: 31226
   username: admin
   password: 
   sslEnabled: true
   telemetryAllowed: false
```
and ran example.springdata.gremlin.Application. But it failed with:
```
2019-02-05 14:36:02.224 ERROR 10536 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Invocation of init method failed; nested exception is com.microsoft.spring.data.gremlin.exception.GremlinQueryException: unable to complete query from gremlin; nested exception is java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: No such property: g for class: Script23
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at example.springdata.gremlin.Application.main(Application.java:67) [classes/:na]
```

**Comment by Incarnation-p-lee** [comment] 2019-02-05 13:41
@frenki-d 
As we have no evn of JanuseGraph and I can only suggestion you 2 ways to validation.

* Update gremlin driver to newest and have a try, see #196 .
* Validate if it can reproduce from gremlin-server, see below configuration:

https://github.com/Microsoft/spring-data-gremlin/blob/91a7a627f0a700df551c35ed2d2d112d5ef50b6a/.travis.yml#L5-L11

**Comment by frenki-d** [comment] 2019-02-05 15:03
@Incarnation-p-lee
Everything works fine with apache-tinkerpop-gremlin-server-3.3.5. So the cause of the problem may be in JanusGraph server settings, but I can't change them. I even have no read access to config files of JanusGraph created by IBM Compose.

May be they don't execute empty-sample.groovy script. It's the only place where I found something similar to my "g":
```
// define the default TraversalSource to bind queries to - this one will be named "g".
globals << [g : graph.traversal()]
```
I deleted this string from script, restarted apache-tinkerpop-gremlin-server and ran Application once more. And yes, I got my exception 
```
com.microsoft.spring.data.gremlin.exception.GremlinQueryException: unable to complete query from gremlin; nested exception is java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: No such property: g for class: Script3
```

So, this error can't be fixed in this lib, it's an IBM Compose "feature" ((

**Comment by jespersm** [comment] 2019-02-05 15:11
> So, this error can't be fixed in this lib, it's an IBM Compose "feature" ((

JanusGraph supports multiple named graphs, not just the 'graph' and 'g' traversals.

The Gremlin client allows you to specify the name of the graph as an alias to DriverRemoteConnection.using(Client client, String remoteTraversalSourceName) which would be very useful to configure in com.microsoft.spring.data.gremlin.common.GremlinConfig. So yes, it really is a feature.

**Comment by jespersm** [comment] 2019-02-05 15:15
Oh, I forgot that this library uses the (old-style) scripts, not TraversalSource. In that case, you can either allow the 'g' used in building the queries to be aliased, or supply an alias map using org.apache.tinkerpop.gremlin.driver.Client.alias(Map<String,String> aliases).

**Comment by jespersm** [comment] 2019-02-05 16:47
> And how can do it? As far as I understand, I can create new graph named "example" by calling from Gremlin console ` def graph = ConfiguredGraphFactory.create("example")`. To create a traversal for this graph I should just call `graph.traversal()`. But how can I tell my JanusGraph to save this traversal name as "g" (for example), so that queries from my Java code will work fine?

See 
https://docs.janusgraph.org/latest/configuredgraphfactory.html#graph-and-traversal-bindings - you should use <graphname>_traversal.

**Comment by frenki-d** [comment] 2019-02-05 17:34
> See
> https://docs.janusgraph.org/latest/configuredgraphfactory.html#graph-and-traversal-bindings - you should use _traversal.
> 
Looks like it doesn't work now without server restart: https://github.com/JanusGraph/janusgraph/issues/1269. That's why I got `Could not alias [g] to [example_traversal] as [example_traversal] not in the Graph or TraversalSource global bindings`

**Comment by jespersm** [comment] 2019-02-05 21:55
@frenki-d : As I read the docs, it should work, possibly pending a 20 second cluster sync period. I'd advice you to try out the user mailing list or Gitter channel for JanusGraph, they are pretty responsive.

**Comment by Incarnation-p-lee** [comment] 2019-02-06 14:26
@frenki-d
I am not sure if we can add some specific configuration when creating gremlin client instance to solve this issue. If we can add one optional config for this.

@jespersm 
We leverage old style because when start the repo, the newest gremlin driver with genetate Traversal script will hang forever when executing the script. I did some investigation on both community and stackoverflow but failure to find perfect solution. As the deadline and time limination, we choose old styple for now. We will plan to investigate that from newest version later.

**Comment by chenrujun** [comment] 2021-03-09 06:58
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 06:58 UTC
Labels: azure-spring, gremlin
