### ISSUE TITLE
[Question] Is the scope of this API just restricted to Azure cosmos DB? Or can it work with any Gremlin API?

### ISSUE THREAD

**Issue by kai18** [microsoft/spring-data-gremlin#203] opened 2019-02-20 10:57 UTC
@Incarnation-p-lee  Will this API work with Neo4j? If I point the configuration towards a Neo4J database.

Is this API supposed to support multiple graph DBs apart from just Cosmos DB? Is it general purpose like Gremlin itslef?

**Comment by Incarnation-p-lee** [comment] 2019-02-20 12:14
Thanks for interesting this package. As you can see from our CI configuration, the repo focus on gremlin-server only and independent to backend db implementation like neo4j, cosmosdb.

https://github.com/Microsoft/spring-data-gremlin/blob/9013c69ff79dae0aaa7c7126d65757987474aacc/.travis.yml#L11-L20

**Comment by kai18** [comment] 2019-02-20 13:04
@Incarnation-p-lee Thank you for the prompt response. I have another query. Neo4j has bolt and https protocols. But by default this API seems to assume the protocol to be wss. Is there some way we can ask it to use bolt or https?

**Comment by RaghavMundhada** [comment] 2019-06-11 10:00
> @Incarnation-p-lee Thank you for the prompt response. I have another query. Neo4j has bolt and https protocols. But by default this API seems to assume the protocol to be wss. Is there some way we can ask it to use bolt or https?

Hey Incarnation-p-lee
Have you figured out how can we use bolt protocol for connecting to neo4j db

**Comment by Incarnation-p-lee** [comment] 2019-06-11 13:04
Thanks for interest this, I am not sure if gremlin-sdk support https or bolt. If so we can support that easy, but if bolt is only for neo4j, there maybe big change there. Could you please file other issue for tracing this ? looks the topic is out of this issue.

**Comment by RaghavMundhada** [comment] 2019-06-12 04:39
Yeah i will create another issue. But is there any way to connect with neo4j without using these protocols? This is the sample project I have created [https://github.com/RaghavMundhada/gremlin-neo4j-connection] . On Running this I am getting the following error 
"Caused by: java.util.concurrent.TimeoutException: Timed out while waiting for an available host - check the client configuration and connectivity to the server if this message persists"

**Comment by chenrujun** [comment] 2021-03-09 06:53
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 06:53 UTC
Labels: azure-spring, gremlin
