### ISSUE TITLE
Application using spring data gremlin 2.1.0 failed to start with error asking to create bean of type GremlinOperations

### ISSUE THREAD

**Issue by PallaviAb24** [microsoft/spring-data-gremlin#202] opened 2019-02-19 11:46 UTC
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
* placeholder

## Current Behavior
* placeholder

## Possible Solution
* placeholder

## Steps to Reproduce (for bugs)
* step-1
* step-2
* ...

## Snapshot Code for Reproduce 
```java
@SpringBootApplication
@EnableGremlinRepositories
@EnableConfigurationProperties
public class PocGremlinApplication {

  public static void main(String[] args) {
    SpringApplication.run(PocGremlinApplication.class, args);
  }

```

	<dependency>
			<groupId>com.microsoft.spring.data.gremlin</groupId>
			<artifactId>spring-data-gremlin</artifactId>
			<version>2.1.0</version>
		</dependency>

Error

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method setGremlinOperations in com.microsoft.spring.data.gremlin.repository.support.GremlinRepositoryFactoryBean required a bean of type 'com.microsoft.spring.data.gremlin.query.GremlinOperations' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.microsoft.spring.data.gremlin.query.GremlinOperations' in your configuration.

**Comment by Incarnation-p-lee** [comment] 2019-02-19 14:18
@PallaviAb24 
Thanks for your issue. Could you please share more information about this ? like the spring boot version you using with spring-data-gremlin 2.1.0.

**Comment by PallaviAb24** [comment] 2019-02-20 07:16
Spring boot version is 2.1.3.RELEASE

**Comment by softwaremagico** [comment] 2019-05-28 16:26
I am facing exactly the same issue with Spring boot 2.1.3.RELEASE and spring-data-gremlin 2.1.2. 

My spring boot app has:
```
@SpringBootApplication
@ComponentScan
@EnableGremlinRepositories(basePackages = "com.my.model")
@EnableConfigurationProperties(GremlinProperties.class)
@PropertySource("classpath:application.yaml")
@EnableSwagger2
@EnableAspectJAutoProxy
public class MyServer {
```

**Comment by Incarnation-p-lee** [comment] 2019-05-29 01:06
Spring boot 2.1.x and spring boot 2.0.x referenced by spring data commons has some breaking changes, and spring boot gremlin following the version from spring data, 2.1.x is for spring boot 2.1.x and 2.0.x is for spring boot 2.0.x.
As I know, that error message should be caused by imcompatible version, could u please provide the minimal code to reproduce this issue ?

**Comment by softwaremagico** [comment] 2019-05-29 08:12
I found a workaround that skip this problem. In fact, if I create a spring boot configuratuion file and address from my main application class, seems working. 

```
@SpringBootApplication
@EnableSwagger2
@EnableAspectJAutoProxy
public class MyServer {
```
With moving all gremlin related annotations to a configuration file.
```
@Configuration
@EnableGremlinRepositories(basePackages = "com.my.model")
@EnableConfigurationProperties(GremlinProperties.class)
@PropertySource("classpath:application.yaml")
@EntityScan
public class GremlinConfiguration extends AbstractGremlinConfiguration {
```
This error dissapear and the application works fine. I am not sure if this information can help you to understand the causes of the error.

**Comment by chenrujun** [comment] 2021-03-09 06:53
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 06:53 UTC
Labels: azure-spring, gremlin
