### ISSUE TITLE
GremlinSource - Vertex/Edge/Graph - Writer/Reader incompatible with Jacoco 

### ISSUE THREAD

**Issue by dbeaudry92** [microsoft/spring-data-gremlin#205] opened 2019-02-25 19:57 UTC
Tests run with [Jacoco](https://www.jacoco.org/) fail with the following error:
```
java.lang.IllegalArgumentException: persistence property should not be null
```

Jacoco adds a field named _$jacocoData_ to domain objects to collect test results.

When writers/readers iterate through  domain objects fields, it eventualy gets to the $jacocoData field. There is no corresponding PersistenceProperty defined in the converter for this field, therefore this line: 
__@Assert.notNull(property, "persistence property should not be null");__ raise an exception.

The problem is in the following classes:
* GremlinSourceEdgeReader
* GremlinSourceEdgeWriter
* GremlinSourceGraphReader
* GremlinSourceGraphWriter
* GremlinSourceVertexReader
* GremlinSourceVertexWriter
 

See atached project as an example of such error.

[gremlin-jacoco-example.zip](https://github.com/Microsoft/spring-data-gremlin/files/2902363/gremlin-jacoco-example.zip)

**Comment by Incarnation-p-lee** [comment] 2019-02-26 01:23
@dbeaudry92 
Thanks for issue that.
Actually, we have try that plugin before and decide not to leverage it as it may inject some fields implicitly. From our side, it is not reasonable enough to adjust the code for one code coverage tool.

How do you think of it ?

**Comment by dbeaudry92** [comment] 2019-02-26 16:38
Thank you @Incarnation-p-lee,

Would it be harmfull to simply ignore fields unknown to the converter?
I tested the following modification to all reader/writer.
```
// Assert.notNull(property, "persistence property should not be null");
if (property == null) {
    continue;
}
```

By adding the Jacoco pluggin to the spring-data-gremlin pom.xml, when issuing a maven test, there is still one test that fails: __MappingGremlinConverterUnitTest.testMappingGremlinConverterGetter()__. The test can be corrected by removing the following instruction:
```
Assert.assertEquals(fields.length, 2);
``` 
Does this instruction tests the org.apache.commons.lang3.reflect.FieldUtils librairy?

**Comment by Incarnation-p-lee** [comment] 2019-02-27 01:05
@dbeaudry92 
Thanks for so many details. The purpose of that test is try to make sure that the class definition is not polluted by some plugin. @sophiaso Have you get any idea of the risk with below change ?

**Comment by Incarnation-p-lee** [comment] 2019-02-27 01:23
@dbeaudry92 
For now, I may not get some risk about this change. If we ignore all null PersistentProperty, that should be transparent to both the read and write process. Can you file one PR for this ?

**Comment by dbeaudry92** [comment] 2019-02-28 15:17
I tried to push a new branch (#205), using htttps or SSL. I get the following error:
```
C:\workspace\spring-data-gremlin>git push origin #205
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
ERROR: Permission to Microsoft/spring-data-gremlin.git denied to dbeaudry92.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Incarnation-p-lee** [comment] 2019-03-01 00:50
@dbeaudry92 
Thanks a lot, my apologize that here may be some invite here. Could you please help to check mail and accept the link ?

**Comment by dbeaudry92** [comment] 2019-03-05 17:16
@Incarnation-p-lee, my email was not valid anymore. My apologize, I just updated today. Can you resend the invite?

**Comment by Incarnation-p-lee** [comment] 2019-03-06 00:56
@dbeaudry92 
Done, please check your email.

**Comment by dbeaudry92** [comment] 2019-03-12 04:10
Pull request is Done

**Comment by dbeaudry92** [comment] 2019-03-13 02:24
Thank you @Incarnation-p-lee  for the merge into Master

**Comment by Incarnation-p-lee** [comment] 2019-03-13 02:33
np, thanks for your contribution and effort.

**Comment by voplex95** [comment] 2019-03-28 13:42
@Incarnation-p-lee I have got similar validation failures using following components:

- `spring-data-gremlin-boot-starter` 2.1.2
- Gremlin Server 3.4.1 with `orientdb-gremlin` driver (3.0.17)
- OrientDB 3.0.17

I get an exception `Caused by: java.lang.IllegalArgumentException: should contain id property` while trying to save vertex. And actually it persists OK, but when it tries to perform that validation it gets a result map of wrong structure. I believe it expects a `Vertex` as a result, but gets a one-element `List<Vertex>`.

I couldn't find any compatibility matrix. Do you have any assumption why it does not work in my case?

**Comment by Incarnation-p-lee** [comment] 2019-03-28 13:52
@voplex95 
Thanks for issue this, it is known issue that gremlin-server 3.4.x has breaking changes for query response json format.

**Comment by voplex95** [comment] 2019-03-28 14:27
@Incarnation-p-lee I believe I had the same thing using Gremlin Server of the version 3.3.5. What is the last version I can safely use?

**Comment by Incarnation-p-lee** [comment] 2019-03-28 14:39
@voplex95 
You can reference our CI test env.

https://github.com/Microsoft/spring-data-gremlin/blob/c94d36c57e6617d17106ab5dea504ce73bdbcc07/.travis.yml#L11-L13

**Comment by chenrujun** [comment] 2021-03-09 06:59
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues

**Closed by chenrujun** 2021-03-09 06:59 UTC
Labels: azure-spring, gremlin
