### ISSUE TITLE
Can not Save basic Vertex

### ISSUE THREAD

**Issue by mingjinc** [microsoft/spring-data-gremlin#230] opened 2019-06-24 09:46 UTC
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
Client is inserted to db

## Current Behavior
Occur error while save
Error message as below
Exception in thread "main" java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.ibm.ca.service.architecture.Application.main(Application.java:56)
Caused by: java.lang.IllegalArgumentException: should contain id property
	at org.springframework.util.Assert.isTrue(Assert.java:118)
	at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultVertexReader.validate(GremlinResultVertexReader.java:36)
	at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultVertexReader.read(GremlinResultVertexReader.java:52)
	at com.microsoft.spring.data.gremlin.conversion.source.AbstractGremlinSource.doGremlinResultRead(AbstractGremlinSource.java:144)
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.recoverDomain(GremlinTemplate.java:341)
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.findByIdInternal(GremlinTemplate.java:231)
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.findById(GremlinTemplate.java:242)
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.existsById(GremlinTemplate.java:370)
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.notExistsById(GremlinTemplate.java:365)
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.save(GremlinTemplate.java:274)
	at com.microsoft.spring.data.gremlin.repository.support.SimpleGremlinRepository.save(SimpleGremlinRepository.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy44.save(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy44.save(Unknown Source)
	at com.ibm.ca.service.architecture.Application.run(Application.java:71)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
	... 5 more

## Possible Solution
* placeholder

## Steps to Reproduce (for bugs)
* step-1
* step-2
* ...

## Snapshot Code for Reproduce 
```java
@Vertex(label = "Client")
public class Client {

    @Id
    private String id;
    
    private String _id;

    private String name;
   
    private String userId;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String get_id() {
		return _id;
	}

	public void set_id(String _id) {
		this._id = _id;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
         }
}



@SpringBootApplication
public class Application implements CommandLineRunner {

    @Autowired
    private ClientRepository repository;
    
	public static void main(String[] args) {
       
        	SpringApplication.run(Application.class, args);
      
    }

    public void run(String... var1) throws Exception {
        final Client client = new Client();
        client.setId("1211");
        client.set_id("xxxxxxxxxxxxxxxx");
        client.setName("dsfdfsadfd");
        client.setUserId("sdafsdaf");
        
        repository.save(client);
 
    }
}



## Branch
* placeholder

## Your Environment
* Version used:
* Operating System and version (desktop or mobile):
* SDK version:

**Comment by mingjinc** [comment] 2019-06-24 09:47
I am using Gremlin Server with Neo4j as storage. 
Gremlin Console can create successfully, but failed with Spring-Data-Gremlin

**Comment by Incarnation-p-lee** [comment] 2019-06-25 00:50
Thanks a lot for you issue, could you please share more information about spring-data-gremlin version, as well as spring boot version ?

**Comment by mingjinc** [comment] 2019-06-25 01:09
spring boot version: 2.1.0.RELEASE
spring-data-gremlin version: 2.1.2

Below is my pom.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ibm.ca.service.architecture</groupId>
    <artifactId>ca-service-architecture</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.0.RELEASE</version>
        <relativePath/>
    </parent>

    <dependencies>
    	<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-commons</artifactId>
        </dependency>
        <dependency>
    		<groupId>com.microsoft.spring.data.gremlin</groupId>
		    <artifactId>spring-data-gremlin</artifactId>
		    <version>2.1.2</version>
		</dependency>
        <dependency>
            <groupId>org.opencypher.gremlin</groupId>
            <artifactId>translation</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.7.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by RaghavMundhada** [comment] 2019-06-25 13:40
Did you get this working ?
I am using 
spring boot version: 2.0.5.RELEASE
spring-data-gremlin version: 2.1.2

and getting the same error

**Comment by mingjinc** [comment] 2019-06-25 14:17
Can not work. 
Waiting for the response..

**Comment by Incarnation-p-lee** [comment] 2019-06-26 05:06
@RaghavMundhada 
spring-data-gremlin version: 2.1.2 is for spring boot 2.1.x.

@mingjinc 
We will try to reproduce this from our env.

**Comment by mingjinc** [comment] 2019-07-01 01:12
@Incarnation-p-lee any updates on that? or could u provide me some other spring-data-gremlin/spring-boot compatible version i could try?

**Comment by Incarnation-p-lee** [comment] 2019-07-02 00:03
@mingjinc 
Sorry for late response, Could you please share more configuration for your code ? as well as the backend db you are using. Looks cannot reproduce your issue from my env.
```
 :: Spring Boot ::        (v2.1.0.RELEASE)

2019-07-02 08:01:34.288  INFO 17000 --- [           main] c.e.gremlintest.GremlinTestApplication   : Starting GremlinTestApplication on panli with PID 17000 (C:\Users\panli\Desktop\gremlin-test\target\classes started by panli in C:\Users\panli\Desktop\gremlin-test)
2019-07-02 08:01:34.292  INFO 17000 --- [           main] c.e.gremlintest.GremlinTestApplication   : No active profile set, falling back to default profiles: default
2019-07-02 08:01:34.759  INFO 17000 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2019-07-02 08:01:34.827  INFO 17000 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 65ms. Found 1 repository interfaces.
2019-07-02 08:01:37.234  INFO 17000 --- [           main] c.e.gremlintest.GremlinTestApplication   : Started GremlinTestApplication in 3.307 seconds (JVM running for 5.328)
2019-07-02 08:02:24.519  INFO 17000 --- [           main] o.a.tinkerpop.gremlin.driver.Connection  : Created new connection for ws://localhost:8889/gremlin
2019-07-02 08:02:24.532  INFO 17000 --- [           main] o.a.tinkerpop.gremlin.driver.Connection  : Created new connection for ws://localhost:8889/gremlin
2019-07-02 08:02:24.533  INFO 17000 --- [           main] o.a.t.gremlin.driver.ConnectionPool      : Opening connection pool on Host{address=localhost/127.0.0.1:8889, hostUri=ws://localhost:8889/gremlin} with core size of 2
2019-07-02 08:02:24.668  INFO 17000 --- [           main] c.e.gremlintest.GremlinTestApplication   : Client(id=1211, _id=xxxxxxxxxxxxxxxx, name=dsfdfsadfd, userId=sdafsdaf)
```

**Comment by georgschmidtdumont** [comment] 2019-07-10 06:32
Hi @Incarnation-p-lee,

I am experiencing the same issue when running the provided example. I am using a local instance of the Gremlin Server. The server config is as follows:

```
host: localhost
port: 8182
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphs: {
  graph: conf/tinkergraph-empty.properties}
scriptEngines: {
  gremlin-groovy: {
    plugins: { org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
               org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]}}}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { ioRegistries: [org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV3d0] }}             # application/vnd.gremlin-v3.0+gryo
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}                                                                       # application/vnd.gremlin-v3.0+gryo-stringd
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV3d0] }}         # application/json
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1 }                                                                                                            # application/vnd.graphbinary-v1.0
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
  - { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000}}
strictTransactionManagement: false
idleConnectionTimeout: 0
keepAliveInterval: 0
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536
ssl: {
  enabled: false}
```

And when I run the example I get the following stacktrace:

```
2019-07-10 08:27:13.301  INFO 21572 --- [           main] o.a.tinkerpop.gremlin.driver.Connection  : Created new connection for ws://localhost:8182/gremlin
2019-07-10 08:27:13.308  INFO 21572 --- [           main] o.a.tinkerpop.gremlin.driver.Connection  : Created new connection for ws://localhost:8182/gremlin
2019-07-10 08:27:13.309  INFO 21572 --- [           main] o.a.t.gremlin.driver.ConnectionPool      : Opening connection pool on Host{address=localhost/127.0.0.1:8182, hostUri=ws://localhost:8182/gremlin} with core size of 2
2019-07-10 08:27:13.485  WARN 21572 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: should contain a type property
2019-07-10 08:27:13.487  INFO 21572 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-07-10 08:27:13.496  INFO 21572 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-07-10 08:27:13.505 ERROR 21572 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: should contain a type property
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at example.springdata.gremlin.Application.main(Application.java:67) [classes/:na]
Caused by: java.lang.IllegalArgumentException: should contain a type property
	at org.springframework.util.Assert.isTrue(Assert.java:118) ~[spring-core-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultsGraphReader.processResult(GremlinResultsGraphReader.java:55) ~[spring-data-gremlin-2.1.0.jar:2.1.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_191]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_191]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_191]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_191]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_191]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_191]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_191]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_191]
	at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultsGraphReader.read(GremlinResultsGraphReader.java:45) ~[spring-data-gremlin-2.1.0.jar:2.1.0]
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.recoverGraphDomain(GremlinTemplate.java:359) ~[spring-data-gremlin-2.1.0.jar:2.1.0]
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.insert(GremlinTemplate.java:152) ~[spring-data-gremlin-2.1.0.jar:2.1.0]
	at com.microsoft.spring.data.gremlin.query.GremlinTemplate.save(GremlinTemplate.java:273) ~[spring-data-gremlin-2.1.0.jar:2.1.0]
	at com.microsoft.spring.data.gremlin.repository.support.SimpleGremlinRepository.save(SimpleGremlinRepository.java:45) ~[spring-data-gremlin-2.1.0.jar:2.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.sun.proxy.$Proxy80.save(Unknown Source) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at com.sun.proxy.$Proxy80.save(Unknown Source) ~[na:na]
	at example.springdata.gremlin.Application.setup(Application.java:79) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	... 18 common frames omitted
```

I am also building a POC for our use case where I experience the issue as well. Please let me know if I can/should provide any other information that might help resolve this issue.

**Comment by Incarnation-p-lee** [comment] 2019-07-10 06:35
you can follow this [config](https://github.com/microsoft/spring-data-gremlin/blob/d870e0d91b45de3bca36c4b649d66fbcdd544736/src/test/resources/application.properties)

**Comment by georgschmidtdumont** [comment] 2019-07-10 06:47
Thanks for the quick response.

I am using the following config:
```
gremlin:
  endpoint: localhost
  port: 8182
  #username: your-username
  #password: your-password
  #sslEnabled: false
  #telemetryAllowed: true
```

I do not believe that the config is the problem since the connection to the Gremlin server is established successfully.
When I remove line 79 from `Application.java`, where the `Network` is saved, the application starts successfully and no errors occur (see console output below).

```
AI: INFO 10-07-2019 08:44, 1: Configuration file has been successfully found as resource
AI: INFO 10-07-2019 08:44, 1: Configuration file has been successfully found as resource
2019-07-10 08:44:27.056  INFO 5164 --- [           main] o.a.tinkerpop.gremlin.driver.Connection  : Created new connection for ws://localhost:8182/gremlin
2019-07-10 08:44:27.063  INFO 5164 --- [           main] o.a.tinkerpop.gremlin.driver.Connection  : Created new connection for ws://localhost:8182/gremlin
2019-07-10 08:44:27.063  INFO 5164 --- [           main] o.a.t.gremlin.driver.ConnectionPool      : Opening connection pool on Host{address=localhost/127.0.0.1:8182, hostUri=ws://localhost:8182/gremlin} with core size of 2
2019-07-10 08:44:27.660  INFO 5164 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-07-10 08:44:27.956  INFO 5164 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2019-07-10 08:44:27.958  INFO 5164 --- [           main] example.springdata.gremlin.Application   : Started Application in 6.393 seconds (JVM running for 7.566)
```

**Comment by Incarnation-p-lee** [comment] 2019-07-10 06:54
I am sorry, line 79 of Application.java is ?

**Comment by georgschmidtdumont** [comment] 2019-07-10 06:55
In line 79 of Application.java the `Network` Entity is saved.

`this.networkRepo.save(this.network);`

**Comment by Incarnation-p-lee** [comment] 2019-07-10 06:57
OK. I see, may enhance the sample later. Thank a lot.

**Comment by mingjinc** [comment] 2019-07-25 10:34
@Incarnation-p-lee i think i find the reason. 
1. our db is janusgraph, it does not support @id as String type. can it support if we do not provide @id ? Did this library verified in Janusgraph? How could I resolve this issue? 
2. Another one is that could we do transaction control if using this library? for example, we have multiple repositories to do different operation, but we need them in one transaction. As there has no annotation to support it? any other way to do it? like manually start and commit, close. 

thx

**Comment by samjkonat** [comment] 2019-09-16 19:48
I am getting the same problem. I am testing Spring data gremlin connected to a Gremlin server. When I run the tests in the example code, I get the exception saying 'should contain a property type'.

The exception is thrown at the following line:
`this.networkRepo.save(this.network);`

I also tried saving a person object, but then I got the exception with message 'should contain id property'.

**Comment by Tin-Nguyen** [comment] 2019-09-28 11:17
I'm facing the same problem. Currently I'm using a `try...catch` to bypass the error `java.lang.IllegalArgumentException: should contain id property` as the data still be saved into my JanusGraph database successfully, but it seems when the `spring-data-gremlin` library is trying to sync the generated id field from JanusGraph, it got an issue. Please let me know if you need more information. Here is what I"m using in my application:
- Spring Boot: 2.1.8.RELEASE
- spring-data-gremlin: 2.1.7
- Java 8

**Comment by arvind-das** [comment] 2020-07-20 17:55
Hi @Tin-Nguyen , the linked issue is very old and one is not sure if that is ever going to be merged. This is a critical thing for this library to embed into our project else it will not be productive to` try catch` every time we perform a save operation. Please look into this urgently. Is it actively being looked upon ?

**Comment by ADBalici** [comment] 2020-08-27 11:39
hey team? any update on this? this is quite a critical merge

**Comment by seanli1988** [comment] 2020-09-07 07:20
@ADBalici can you tell us your scenario? Which database are you connecting to?

**Comment by ADBalici** [comment] 2020-09-07 13:33
that would be JanusGraph

**Comment by seanli1988** [comment] 2020-09-08 02:09
I'm closing this issue as supporting JanusGraph is not on our prioritized list of scenarios and we are in the process of deprecating the Gremlin API.

**Closed** 2020-09-08 02:28 UTC
Labels: azure-spring, gremlin
